### ISSUE TITLE
Failing to correctly parse AWS CloudFormation Yaml

### ISSUE THREAD

**Issue by godeater** [jborean93/PowerShell-Yayaml#22]
Hi there,

I'm struggling to use this module to parse an AWS CloudFormation template. The template is mostly strict YAML, but AWS define some "intrinsic functions" which can appear as tag values with a '!'prefix on the function name, followed by its arguments, e.g.

```yaml
Content:
  S3Bucket: !Ref SomeS3Bucket
```
or
```yaml
OtherContent:
  BucketArn: !Sub '{"NodeJsCfnResponseArn":"${LambdaLayerNodeJsCfnResponse}", "NodeJsSendEmailArn":"${LambdaLayerNodeJsSendEmail}"}'
```

When I try to convert these templates to a PowerShell object using ConvertFrom-Yaml, the function arguments seem to be present in the resulting object, but the function itself has gone completely. Contrived example below:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: A contrived CloudFormation Template
Resources:
  KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/AKMSKey
      TargetKeyId: !Ref AKMSKey
```
Now run this through the module:
```powershell
# $Yaml is content as above
$Template = $Yaml | ConvertFrom-Yaml
$Template.Resources.KmsKeyAlias.Properties

Name                           Value
----                           -----
AliasName                      alias/AKMSKey
TargetKeyId                    AKMSKey
```

Where really I'd prefer to see:
```powershell
Name                           Value
----                           -----
AliasName                      alias/AKMSKey
TargetKeyId                    !Ref AKMSKey
```

I tried looking at your docs on adding custom schemas, and apparently that's over my YAML event horizon, as I couldn't make head or tail of it.

Any pointers?
